// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE_pEK0HhS5fcgUvlOkOQdV_PXRJhfkA4',
    appId: '1:369714629703:web:00e271a0d858d9c44f7562',
    messagingSenderId: '369714629703',
    projectId: 'apcs-quiz-app',
    authDomain: 'apcs-quiz-app.firebaseapp.com',
    storageBucket: 'apcs-quiz-app.appspot.com',
    measurementId: 'G-DRBD50WCNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc_QOiJDzEGGi1KMRc15IT2xgMHpNNX4I',
    appId: '1:369714629703:android:7c204ebbb67399aa4f7562',
    messagingSenderId: '369714629703',
    projectId: 'apcs-quiz-app',
    storageBucket: 'apcs-quiz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUSRMIwg3Z1yLCZfrufF9O6GW_NYuPezw',
    appId: '1:369714629703:ios:dbef15eb83dd56c94f7562',
    messagingSenderId: '369714629703',
    projectId: 'apcs-quiz-app',
    storageBucket: 'apcs-quiz-app.appspot.com',
    iosClientId: '369714629703-fm7s7ge2oamh0koa890o93gc66lpabro.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUSRMIwg3Z1yLCZfrufF9O6GW_NYuPezw',
    appId: '1:369714629703:ios:dbef15eb83dd56c94f7562',
    messagingSenderId: '369714629703',
    projectId: 'apcs-quiz-app',
    storageBucket: 'apcs-quiz-app.appspot.com',
    iosClientId: '369714629703-fm7s7ge2oamh0koa890o93gc66lpabro.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseQuizApp',
  );
}
